# Generated by Django 5.0.11 on 2025-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='account_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='account_type'),
        ),
    ]
